### ISSUE TITLE
Graphics/display issue

### ISSUE THREAD

**Issue by jaimbo** [jaimbo/twrp_android_device_doogee_p3pro#1]
@lopestom I'm trying to get a device tree for TWRP/OrangeFox recovery up and working for this device and I think I have a lot of the progress complete but I've not been able to solve this issue with the display/graphics rendering being off. I've been using your gists/guides which have been a great resource but I haven't found anything about how to solve this specific issue.

Is this something you've seen before? Any ideas?

![image](https://github.com/jaimbo/twrp_android_device_doogee_p3pro/assets/2665096/0c10fe12-90b3-46b2-afeb-c1a204a112a5)
![image](https://github.com/jaimbo/twrp_android_device_doogee_p3pro/assets/2665096/38b10056-7ec8-4e68-ba35-e6d126c20b7f)

**Comment by jaimbo** [comment]
I solved this issue! I had to use TARGET_RECOVERY_FORCE_PIXEL_FORMAT := RGBX_8888 #DRECOVERY_RGBX

**Comment by lopestom** [comment]
> I solved this issue! I had to use TARGET_RECOVERY_FORCE_PIXEL_FORMAT := RGBX_8888 #DRECOVERY_RGBX

Great.
I'm in doubts

1. Since you put MT6789 device so it's have DOWNLOAD MODE?? Your device is Samsung? Your device really have that?

https://github.com/jaimbo/twrp_android_device_doogee_p3pro/blob/50444598e2fe813f02955b1943475b71069752cc/BoardConfig.mk#L131C6-L131C29

2. You unpacked img file to know if this file already compiled?
https://github.com/jaimbo/twrp_android_device_doogee_p3pro/blob/50444598e2fe813f02955b1943475b71069752cc/device.mk#L86

Since I know, TeamWin put that in source code to compile with other files in a grouped manner. But......

Same doubt with snapuserd.rc files. https://github.com/jaimbo/twrp_android_device_doogee_p3pro/blob/50444598e2fe813f02955b1943475b71069752cc/recovery/root/system/etc/init/snapuserd.rc
Two same files in the DT?
https://github.com/jaimbo/twrp_android_device_doogee_p3pro/blob/50444598e2fe813f02955b1943475b71069752cc/recovery/root/snapuserd.rc
If you call compile snapuserd files so that's compiled from source code. So snapuserd.rc compiled too from that.

3. I really not see `\cache` partition in your sock fstab. 
https://github.com/jaimbo/twrp_android_device_doogee_p3pro/blob/master/recovery/root/first_stage_ramdisk/fstab.mt8781

What's reason you place in the recovery.fstab & twrp.flag files??
https://github.com/jaimbo/twrp_android_device_doogee_p3pro/blob/50444598e2fe813f02955b1943475b71069752cc/recovery/root/system/etc/twrp.flags#L8
https://github.com/jaimbo/twrp_android_device_doogee_p3pro/blob/50444598e2fe813f02955b1943475b71069752cc/recovery/root/system/etc/recovery.fstab#L14
Therefore your DT has 2 recovery.fstab?
Two ways for fix that:
- Erase `recovery/root/system/etc/recovery.fstab`;
- Copy `\recovery.fstab` to `recovery\root\system\ect\`.

After that if your recovery.fstab is same of twrp.flag??
Yes.
So put this:
```ruby
# Properties
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery.fstab
```
No.
Not put that. But fix correctly recovery.fstab and in the correct folder!

4. Okay, you not choose the encryption mode
https://github.com/jaimbo/twrp_android_device_doogee_p3pro/blob/50444598e2fe813f02955b1943475b71069752cc/BoardConfig.mk#L167
What's reason you have this?
https://github.com/jaimbo/twrp_android_device_doogee_p3pro/blob/50444598e2fe813f02955b1943475b71069752cc/recovery/root/init.recovery.mt8781.rc
and very files to decrypt??
https://github.com/jaimbo/twrp_android_device_doogee_p3pro/tree/50444598e2fe813f02955b1943475b71069752cc/recovery/root/vendor

The stock init.recovery.mt8781.rc file is not good to start Custom Recovery?

It's good to know that you corrected the color graphics.
I'm happy for you. : ]

**Comment by jaimbo** [comment]
I think these should be all of the relevant stock files for the fstabs from the stock firmware, prefixed with where they came from. (I added .txt to allow uploading to Github)
[vendor_boot.first_stage_ramdisk.fstab.mt8781.txt](https://github.com/jaimbo/twrp_android_device_doogee_p3pro/files/14903575/vendor_boot.first_stage_ramdisk.fstab.mt8781.txt)
[vendor_boot.fstab.mt8781.txt](https://github.com/jaimbo/twrp_android_device_doogee_p3pro/files/14903576/vendor_boot.fstab.mt8781.txt)
[vendor_boot.system.etc.recovery.fstab.txt](https://github.com/jaimbo/twrp_android_device_doogee_p3pro/files/14903577/vendor_boot.system.etc.recovery.fstab.txt)

[vendor_boot.first_stage_ramdisk.fstab.emmc.txt](https://github.com/jaimbo/twrp_android_device_doogee_p3pro/files/14903573/vendor_boot.first_stage_ramdisk.fstab.emmc.txt)
[vendor_boot.first_stage_ramdisk.fstab.mt6789.txt](https://github.com/jaimbo/twrp_android_device_doogee_p3pro/files/14903574/vendor_boot.first_stage_ramdisk.fstab.mt6789.txt)

**Comment by lopestom** [comment]
> @lopestom
> 
> 1. I had not tested the download mode, I thought it would work to boot into the EDL mode on MTK but it does not seem to work as expected  - I will remove this, thank you :)

EDL => MTK devices not have EDL Mode.

> 2.Yes, snapuserd is compiling fine - I had to remove the libgflags line from the remove section in the minimal manifest but it works! I did not know that the snapuserd.rc file will come with the compiled version, I will test this and update the tree to remove the duplicate file!
For compiling snapuserd and call modules:
```
# Enabling this property, will improve OTA install time
$(call inherit-product, $(SRC_TARGET_DIR)/product/virtual_ab_ota/compression.mk)
```
or
```
# For devices that are not GKI-capable (eg do not have vendor_boot),
# snapuserd.ramdisk is included rather than snapuserd.vendor_ramdisk.
$(call inherit-product, $(SRC_TARGET_DIR)/product/virtual_ab_ota/compression_retrofit.mk)
```
But unfortunately with twrp-12.1 minimal manifest that not work!!
Obvius you look minimal manifest has only twrp-11 and twrp-12.1 and obvius need twrp-13.
Because that, read in the 4.
> 3. Yes, I think you are right - though I can see it in the fstab.emmc - is there a way to check on the device if this partition is present?

`fastboot getvar all`
loook if have \*\cache partition

But I'm absolutely sure it won't exist. Most devices with boot_ramdisk do not have \cache partitions, but only Xiaomi devices use the \*\rescue partition for their own firmware actions. Sometimes Realme on some of its devices, not all.

> I think I have done the opposite, add recovery.fstab to recovery/root/system/etc/recovery.fstab and copied that to correct location - does this work too?

Not oposite, same that I wrote. copied/overwrite/deleted to copy/create other..... The important is have the correct recovery.fstab 

> So I don't need both recovery.fstab and twrp.flags at the same time?

Here it is your choice because it depends on these and particularities. As far as I know, it was introduced in the TWRP source code to use a script that searches all fstab files. Therefore, there is already one in `/recovery/root/first_stage_ramdisk\fstab.*` and so the code checks it.
But I really prefer to directly put recovery.fstab in `\recovery\root\system\etc\` because I've been used to it for a few years and I can also change/choose the partitions that are important to mount initially. Then there is recovery.fstab as in fstab stock and twrp.flag to choose partitions that each author wants or needs.
But many other users just put recovery.fstab (but written as twrp.flag/fstab) and Custom Recovery should normally mount the partitions, as well as perform the tasks described in the flag line.

> 4. I do want to get decrypt working - the files are added but decrypt is not yet working - do you have any advice on how to get it to work? I was following your guide but with the setup currently in the repo, the device get's stuck on OrangeFox logo when crypto is enabled :(
Well, I still haven't seen if there is a twrp-13. Did you see?
So if it really doesn't exist, how will encryption/decryption work?
Some authors are installing and modifying the source code on their computers. This way, they can make encryption/decryption work (depends on the encryption mode). Obviously there is an android-13 both in bootable recovery in the TeamWin repository and in Omni. But the fact that there is no twrp-13 in minimal manifest means that I cannot test it myself on devices with Android 13.
So while I don't have a great computer and rely on online compilation, I also have to wait for TeamWin to create and update the minimal manifest with twrp-13.

I say this because in Android 13, encryption/decryption files have more files in dependency, related to -V2 files.
<details><summary>Click to open</summary>
<p>

![SSs](https://private-user-images.githubusercontent.com/101643020/305506177-39326edb-bc18-4078-86f0-94240adeb95c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MTU3MzQsIm5iZiI6MTcxMjYxNTQzNCwicGF0aCI6Ii8xMDE2NDMwMjAvMzA1NTA2MTc3LTM5MzI2ZWRiLWJjMTgtNDA3OC04NmYwLTk0MjQwYWRlYjk1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQyMjMwMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzljMjU3ODIzMmQwN2YwMjYyMTEyYzQ4ZjlmZGVmZTQ3OGM0Nzk5M2EwNmJhMDVhNmI4ZWM0MjkzZDI2YTAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hmHZM_OImhoKdo4vVPUHiJcUCw7uffuKU3abfaiveBw)
</p>
</details>

I see other autors decrypt with km_4.1, but has keystore2 and keymint decrypt binaries. All need testing.
So for that you can add my avatar as colaborator in the Settings - colaborator - lopestom; if you want.
If yes, open other issue : Encrypt-Decrypt
We write more in that.

**Comment by jaimbo** [comment]
I actually already managed to get decrypt working :)

I need to spend some time and remove unneeded files from the device tree but it works!

Next I need to figure out why MTP isn't working and why I need to disable MTP to get ADB working

**Comment by lopestom** [comment]
> I actually already managed to get decrypt working :)
> 
> I need to spend some time and remove unneeded files from the device tree but it works!
> 
> Next I need to figure out why MTP isn't working and why I need to disable MTP to get ADB working

Great!
I wish the best for you then.

**Comment by lopestom** [comment]
> I actually already managed to get decrypt working :)
> 
> I need to spend some time and remove unneeded files from the device tree but it works!
> 
> Next I need to figure out why MTP isn't working and why I need to disable MTP to get ADB working

Any tests with test-2 branch?

**Comment by lopestom** [comment]
Closed as the issue has solved.
